# -*- coding: utf-8 -*-
"""Ridge sparse_cg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dyXKEoReKFt9mHm_b6fZwEwgDuYT-f7

# Comparing the custom implementation with sklearn Ridge

# Ridge Regression Class
"""

from sklearn.base import BaseEstimator , RegressorMixin
import numpy as np

class RidgeRegression(BaseEstimator, RegressorMixin):
    def __init__(self, alpha=1.0 , learning_rate = 0.01 , epochs = 100):
        self.alpha = alpha
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.intercept_ = None
        self.coef_ = None

    def fit(self , x , y):
        x = np.asarray(x)
        y = np.asarray(y)

        self.coef_ = np.zeros(x.shape[1])
        self.intercept_ = 0
        theta = np.insert(self.coef_ , 0 , self.intercept_)

        x = np.insert(x , 0 , 1 , axis = 1)

        for _ in range(self.epochs):
          theta_der = np.dot(x.T , x).dot(theta) - np.dot(x.T , y)
          theta_der[1:] = theta_der[1:] + self.alpha * theta[1:]

          theta = theta - self.learning_rate * theta_der

        self.coef_ = theta[1:]
        self.intercept_ = theta[0]

        return self


    def predict(self , x_test):
        x_test = np.asarray(x_test)
        return np.dot(x_test, self.coef_) + self.intercept_

"""# Comparing with Scikit-Learn"""

from sklearn.linear_model import Ridge
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split

# Dataset
X, y = load_diabetes(return_X_y=True)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Custom Ridge
my_model = RidgeRegression(
    alpha=1.0,
    learning_rate=0.001,
    epochs=500
)

my_model.fit(X_train, y_train)


# Sklearn Ridge
sk_model = Ridge(alpha=0.001 , solver = 'sparse_cg' , max_iter = 500 )

sk_model.fit(X_train, y_train)


# Cross-check
print("Custom Ridge")
print("Coefficients:", my_model.coef_)
print("Intercept:", my_model.intercept_)
print("r2_score:" , my_model.score(X_test , y_test))

print("\nSklearn Ridge")
print("Coefficients:", sk_model.coef_)
print("Intercept:", sk_model.intercept_)
print("r2_score:" , sk_model.score(X_test , y_test))