# -*- coding: utf-8 -*-
"""Stochastic Gradient Descent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dyXKEoReKFt9mHm_b6fZwEwgDuYT-f7
"""

from sklearn.base import BaseEstimator , RegressorMixin
import numpy as np

class customSGDRegressor(BaseEstimator , RegressorMixin):
  def __init__(self , epochs = 100 , learning_rate = 0.01):
    self.epochs = epochs
    self.learning_rate = learning_rate
    self.intercept_ = None
    self.coef_ = None

  def fit(self , x_train , y_train):
    x_train = np.asarray(x_train)
    y_train = np.asarray(y_train)

    self.intercept_ = 0
    self.coef_ = np.ones(x_train.shape[1])

    for i in range(self.epochs):
      for j in range(x_train.shape[0]):
        idx = np.random.randint(0 , x_train.shape[0])
        y_hat = np.dot(x_train[idx] , self.coef_) + self.intercept_
        intercept_der = -2 * (y_train[idx] - y_hat)
        coef_der = -2 * (y_train[idx] - y_hat) * x_train[idx]
        self.intercept_ = self.intercept_ - (self.learning_rate * intercept_der)
        self.coef_ = self.coef_ - (self.learning_rate * coef_der)

    return self

  def predict(self , x_test):
    x_test = np.asarray(x_test)
    return np.dot(x_test , self.coef_) + self.intercept_

"""# Load Dataset

"""

from sklearn.metrics import r2_score
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split

df = load_diabetes(return_X_y=True)

x = df[0]
y = df[1]

x_trian , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state=2)

"""# Benchmark: Custom SGDRegressor vs Scikit-Learn"""

from sklearn.linear_model import SGDRegressor

SGD = SGDRegressor(max_iter = 70 , learning_rate = 'constant', eta0=0.01)
SGD.fit(x_trian , y_train)

print("Coef_ : ",SGD.coef_)
print("intercept_ : ",SGD.intercept_)
print("r2_Score : " , r2_score(y_test , SGD.predict(x_test)))

"""## Performance Benchmark Against Scikit-Learn"""

sgd = customSGDRegressor(epochs=45 , learning_rate=0.01)
sgd.fit(x_trian , y_train)

print("Coef_ : ",sgd.coef_)
print("intercept_ : ",sgd.intercept_)
print("r2_Score : " , r2_score(y_test , sgd.predict(x_test)))

