# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10b17rCVASwwq97i8FK5epctKe3LL2ggr

#1. Custom Multiple Linear Regression Class
"""

import numpy as np
from sklearn.base import BaseEstimator , RegressorMixin

class MultipleLinearRegression(BaseEstimator , RegressorMixin):
  def __init__(self):
    self.coef_ = None
    self.intercept_ = None

  def fit(self , x_train , y_train):

    x = np.asarray(x_train)
    y = np.asarray(y_train)

    x = np.insert(x , 0 , 1 , axis = 1)

    betas = np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y)
    self.coef_ = betas[1:]
    self.intercept_ = betas[0]

    return self

  def predict(self , x_test):
    x_test = np.asarray(x_test)
    return np.dot(x_test , self.coef_) + self.intercept_

"""# 2. Sklearn LinearRegression (Benchmark)"""

from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

x,y = load_diabetes(return_X_y = True ,as_frame=True)

x_train , x_test , y_train , y_test = train_test_split(x,y , random_state = 42 , test_size = 0.2)

lr = LinearRegression()
lr.fit(x_train , y_train)

y_pred = lr.predict(x_test)
print(r2_score(y_test , y_pred))

"""# 2. Custom MultipleLinearRegression"""

custom_lr = MultipleLinearRegression()
custom_lr.fit(x_train , y_train)

y2_pred = custom_lr.predict(x_test)

print(r2_score(y_test , y2_pred))